import type { UserProfile, CompanyProfile, TopicResources, Question } from "./types";

export const userProfile: UserProfile = {
  name: "Alex Chen",
  targetCompany: "Amazon",
  studyStreak: 12,
  totalProblems: 247,
  subjects: [
    {
      name: "DSA",
      icon: "Code2",
      overallProgress: 68,
      overallAccuracy: 72,
      topics: [
        {
          topic: "Arrays",
          subtopics: ["Two Pointers", "Sliding Window", "Prefix Sum"],
          progress: 85,
          accuracy: 88,
          practiceCount: 45,
          lastPracticed: "2024-01-15",
          status: "strong",
        },
        {
          topic: "Trees",
          subtopics: ["Binary Trees", "BST", "Tree Traversal"],
          progress: 70,
          accuracy: 75,
          practiceCount: 32,
          lastPracticed: "2024-01-14",
          status: "moderate",
        },
        {
          topic: "Graphs",
          subtopics: ["BFS", "DFS", "Dijkstra", "Union Find"],
          progress: 45,
          accuracy: 52,
          practiceCount: 18,
          lastPracticed: "2024-01-10",
          status: "weak",
        },
        {
          topic: "Dynamic Programming",
          subtopics: ["1D DP", "2D DP", "Knapsack", "LCS"],
          progress: 38,
          accuracy: 45,
          practiceCount: 22,
          lastPracticed: "2024-01-12",
          status: "weak",
        },
        {
          topic: "Linked Lists",
          subtopics: ["Reversal", "Fast/Slow Pointers", "Merge"],
          progress: 90,
          accuracy: 92,
          practiceCount: 28,
          lastPracticed: "2024-01-13",
          status: "strong",
        },
      ],
    },
    {
      name: "DBMS",
      icon: "Database",
      overallProgress: 55,
      overallAccuracy: 65,
      topics: [
        {
          topic: "SQL Queries",
          subtopics: ["Joins", "Subqueries", "Aggregations"],
          progress: 75,
          accuracy: 80,
          practiceCount: 30,
          lastPracticed: "2024-01-14",
          status: "moderate",
        },
        {
          topic: "Normalization",
          subtopics: ["1NF", "2NF", "3NF", "BCNF"],
          progress: 60,
          accuracy: 70,
          practiceCount: 15,
          lastPracticed: "2024-01-11",
          status: "moderate",
        },
        {
          topic: "Transactions",
          subtopics: ["ACID", "Isolation Levels", "Locking"],
          progress: 40,
          accuracy: 50,
          practiceCount: 10,
          lastPracticed: "2024-01-08",
          status: "weak",
        },
        {
          topic: "Indexing",
          subtopics: ["B+ Trees", "Hashing", "Clustered"],
          progress: 45,
          accuracy: 55,
          practiceCount: 12,
          lastPracticed: "2024-01-09",
          status: "weak",
        },
      ],
    },
    {
      name: "Operating Systems",
      icon: "Cpu",
      overallProgress: 62,
      overallAccuracy: 68,
      topics: [
        {
          topic: "Process Management",
          subtopics: ["Scheduling", "Synchronization", "Deadlocks"],
          progress: 70,
          accuracy: 75,
          practiceCount: 20,
          lastPracticed: "2024-01-13",
          status: "moderate",
        },
        {
          topic: "Memory Management",
          subtopics: ["Paging", "Segmentation", "Virtual Memory"],
          progress: 55,
          accuracy: 60,
          practiceCount: 15,
          lastPracticed: "2024-01-10",
          status: "moderate",
        },
        {
          topic: "File Systems",
          subtopics: ["Allocation", "Directory Structure", "I/O"],
          progress: 65,
          accuracy: 70,
          practiceCount: 12,
          lastPracticed: "2024-01-11",
          status: "moderate",
        },
      ],
    },
    {
      name: "Computer Networks",
      icon: "Network",
      overallProgress: 58,
      overallAccuracy: 62,
      topics: [
        {
          topic: "TCP/IP",
          subtopics: ["Handshake", "Flow Control", "Congestion"],
          progress: 65,
          accuracy: 70,
          practiceCount: 18,
          lastPracticed: "2024-01-12",
          status: "moderate",
        },
        {
          topic: "HTTP/HTTPS",
          subtopics: ["Methods", "Status Codes", "TLS"],
          progress: 80,
          accuracy: 85,
          practiceCount: 22,
          lastPracticed: "2024-01-14",
          status: "strong",
        },
        {
          topic: "DNS",
          subtopics: ["Resolution", "Caching", "Records"],
          progress: 50,
          accuracy: 55,
          practiceCount: 10,
          lastPracticed: "2024-01-08",
          status: "weak",
        },
        {
          topic: "Network Security",
          subtopics: ["Firewalls", "VPN", "Encryption"],
          progress: 40,
          accuracy: 45,
          practiceCount: 8,
          lastPracticed: "2024-01-06",
          status: "weak",
        },
      ],
    },
    {
      name: "Aptitude",
      icon: "Brain",
      overallProgress: 72,
      overallAccuracy: 78,
      topics: [
        {
          topic: "Quantitative",
          subtopics: ["Arithmetic", "Algebra", "Geometry"],
          progress: 80,
          accuracy: 85,
          practiceCount: 40,
          lastPracticed: "2024-01-15",
          status: "strong",
        },
        {
          topic: "Logical Reasoning",
          subtopics: ["Puzzles", "Patterns", "Syllogisms"],
          progress: 75,
          accuracy: 80,
          practiceCount: 35,
          lastPracticed: "2024-01-14",
          status: "moderate",
        },
        {
          topic: "Verbal",
          subtopics: ["Reading Comprehension", "Grammar", "Vocabulary"],
          progress: 60,
          accuracy: 68,
          practiceCount: 20,
          lastPracticed: "2024-01-10",
          status: "moderate",
        },
      ],
    },
  ],
};

export const companies: CompanyProfile[] = [
  {
    name: "Amazon",
    logo: "amazon",
    difficulty: "Hard",
    focusAreas: [
      {
        subject: "DSA",
        weight: 40,
        importantTopics: ["Arrays", "Trees", "Graphs", "Dynamic Programming"],
      },
      {
        subject: "System Design",
        weight: 25,
        importantTopics: ["Scalability", "Distributed Systems"],
      },
      {
        subject: "Leadership Principles",
        weight: 20,
        importantTopics: ["Behavioral Questions", "STAR Method"],
      },
      {
        subject: "DBMS",
        weight: 15,
        importantTopics: ["SQL Queries", "Indexing"],
      },
    ],
    interviewRounds: [
      "Online Assessment",
      "Phone Screen",
      "On-site (4-5 rounds)",
    ],
  },
  {
    name: "TCS",
    logo: "tcs",
    difficulty: "Medium",
    focusAreas: [
      {
        subject: "Aptitude",
        weight: 35,
        importantTopics: ["Quantitative", "Logical Reasoning", "Verbal"],
      },
      { subject: "DSA", weight: 25, importantTopics: ["Arrays", "Strings"] },
      {
        subject: "DBMS",
        weight: 20,
        importantTopics: ["SQL Queries", "Normalization"],
      },
      {
        subject: "OS & CN",
        weight: 20,
        importantTopics: ["Process Management", "TCP/IP"],
      },
    ],
    interviewRounds: ["NQT Test", "Technical Interview", "HR Interview"],
  },
  {
    name: "Infosys",
    logo: "infosys",
    difficulty: "Medium",
    focusAreas: [
      {
        subject: "Aptitude",
        weight: 30,
        importantTopics: ["Quantitative", "Logical Reasoning"],
      },
      {
        subject: "DSA",
        weight: 30,
        importantTopics: ["Arrays", "Linked Lists", "Trees"],
      },
      {
        subject: "DBMS",
        weight: 20,
        importantTopics: ["SQL Queries", "Transactions"],
      },
      { subject: "OS", weight: 20, importantTopics: ["Process Management"] },
    ],
    interviewRounds: ["InfyTQ", "Technical Interview", "HR Interview"],
  },
  {
    name: "Google",
    logo: "google",
    difficulty: "Hard",
    focusAreas: [
      {
        subject: "DSA",
        weight: 50,
        importantTopics: ["Graphs", "Dynamic Programming", "Trees", "Arrays"],
      },
      {
        subject: "System Design",
        weight: 30,
        importantTopics: ["Distributed Systems", "API Design"],
      },
      {
        subject: "Behavioral",
        weight: 20,
        importantTopics: ["Googleyness", "Leadership"],
      },
    ],
    interviewRounds: [
      "Phone Screen (2)",
      "On-site (4-5 rounds)",
      "Team Matching",
    ],
  },
];

// Study Resources by Topic
export const studyResources: TopicResources[] = [
  {
    topic: "Arrays",
    subject: "DSA",
    resources: [
      { title: "Two Sum - LeetCode", platform: "LeetCode", url: "https://leetcode.com/problems/two-sum/", type: "practice", difficulty: "Easy" },
      { title: "Best Time to Buy Sell Stock", platform: "LeetCode", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", type: "practice", difficulty: "Easy" },
      { title: "Arrays Data Structure", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/array-data-structure/", type: "article" },
      { title: "Arrays Complete Course", platform: "YouTube", url: "https://www.youtube.com/watch?v=n60Dn0UsbEk", type: "video" },
    ],
  },
  {
    topic: "Trees",
    subject: "DSA",
    resources: [
      { title: "Binary Tree Inorder Traversal", platform: "LeetCode", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", type: "practice", difficulty: "Easy" },
      { title: "Maximum Depth of Binary Tree", platform: "LeetCode", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", type: "practice", difficulty: "Easy" },
      { title: "Binary Search Trees", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/binary-search-tree-data-structure/", type: "article" },
      { title: "Trees Full Course", platform: "YouTube", url: "https://www.youtube.com/watch?v=fAAZixBzIAI", type: "video" },
    ],
  },
  {
    topic: "Graphs",
    subject: "DSA",
    resources: [
      { title: "Number of Islands", platform: "LeetCode", url: "https://leetcode.com/problems/number-of-islands/", type: "practice", difficulty: "Medium" },
      { title: "Clone Graph", platform: "LeetCode", url: "https://leetcode.com/problems/clone-graph/", type: "practice", difficulty: "Medium" },
      { title: "Graph Data Structure", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/", type: "article" },
      { title: "Graph Algorithms Course", platform: "YouTube", url: "https://www.youtube.com/watch?v=tWVWeAqZ0WU", type: "video" },
    ],
  },
  {
    topic: "Dynamic Programming",
    subject: "DSA",
    resources: [
      { title: "Climbing Stairs", platform: "LeetCode", url: "https://leetcode.com/problems/climbing-stairs/", type: "practice", difficulty: "Easy" },
      { title: "House Robber", platform: "LeetCode", url: "https://leetcode.com/problems/house-robber/", type: "practice", difficulty: "Medium" },
      { title: "Longest Common Subsequence", platform: "LeetCode", url: "https://leetcode.com/problems/longest-common-subsequence/", type: "practice", difficulty: "Medium" },
      { title: "DP Patterns", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/dynamic-programming/", type: "article" },
      { title: "Dynamic Programming Tutorial", platform: "YouTube", url: "https://www.youtube.com/watch?v=oBt53YbR9Kk", type: "video" },
    ],
  },
  {
    topic: "Linked Lists",
    subject: "DSA",
    resources: [
      { title: "Reverse Linked List", platform: "LeetCode", url: "https://leetcode.com/problems/reverse-linked-list/", type: "practice", difficulty: "Easy" },
      { title: "Linked List Cycle", platform: "LeetCode", url: "https://leetcode.com/problems/linked-list-cycle/", type: "practice", difficulty: "Easy" },
      { title: "Linked List Guide", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/data-structures/linked-list/", type: "article" },
    ],
  },
  {
    topic: "SQL Queries",
    subject: "DBMS",
    resources: [
      { title: "SQL Practice Problems", platform: "HackerRank", url: "https://www.hackerrank.com/domains/sql", type: "practice" },
      { title: "SQL Tutorial", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/sql-tutorial/", type: "article" },
      { title: "SQL Complete Course", platform: "YouTube", url: "https://www.youtube.com/watch?v=HXV3zeQKqGY", type: "video" },
    ],
  },
  {
    topic: "Normalization",
    subject: "DBMS",
    resources: [
      { title: "Database Normalization", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/normal-forms-in-dbms/", type: "article" },
      { title: "DBMS Normalization Tutorial", platform: "YouTube", url: "https://www.youtube.com/watch?v=UrYLYV7WSHM", type: "video" },
    ],
  },
  {
    topic: "Transactions",
    subject: "DBMS",
    resources: [
      { title: "ACID Properties", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/acid-properties-in-dbms/", type: "article" },
      { title: "Transactions in DBMS", platform: "YouTube", url: "https://www.youtube.com/watch?v=P80Js_qClUE", type: "video" },
    ],
  },
  {
    topic: "Process Management",
    subject: "Operating Systems",
    resources: [
      { title: "Process Scheduling", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/cpu-scheduling-in-operating-systems/", type: "article" },
      { title: "OS Process Management", platform: "YouTube", url: "https://www.youtube.com/watch?v=26QPDBe-NB8", type: "video" },
    ],
  },
  {
    topic: "Memory Management",
    subject: "Operating Systems",
    resources: [
      { title: "Memory Management in OS", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/memory-management-in-operating-system/", type: "article" },
      { title: "Paging and Segmentation", platform: "YouTube", url: "https://www.youtube.com/watch?v=LKYKp_ZzlvM", type: "video" },
    ],
  },
  {
    topic: "TCP/IP",
    subject: "Computer Networks",
    resources: [
      { title: "TCP/IP Model", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/tcp-ip-model/", type: "article" },
      { title: "Networking Course", platform: "YouTube", url: "https://www.youtube.com/watch?v=qiQR5rTSshw", type: "video" },
    ],
  },
  {
    topic: "Quantitative",
    subject: "Aptitude",
    resources: [
      { title: "Aptitude Questions", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/aptitude-questions-and-answers/", type: "practice" },
      { title: "Quantitative Aptitude", platform: "YouTube", url: "https://www.youtube.com/watch?v=vtLj4aWYYhA", type: "video" },
    ],
  },
];

// Questions for Test System
export const questionBank: Question[] = [
  // DSA - Arrays
  {
    id: "dsa-arr-1",
    question: "What is the time complexity of accessing an element in an array by index?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"],
    correctAnswer: 0,
    subject: "DSA",
    topic: "Arrays",
    difficulty: "Easy",
    explanation: "Arrays provide constant time O(1) access to elements using index.",
  },
  {
    id: "dsa-arr-2",
    question: "Which algorithm is used in the Two Sum problem for optimal time complexity?",
    options: ["Binary Search", "Hash Map", "Two Pointers", "Sliding Window"],
    correctAnswer: 1,
    subject: "DSA",
    topic: "Arrays",
    difficulty: "Easy",
    explanation: "Using a hash map allows us to find pairs in O(n) time.",
  },
  {
    id: "dsa-arr-3",
    question: "What is the space complexity of an in-place sorting algorithm?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"],
    correctAnswer: 0,
    subject: "DSA",
    topic: "Arrays",
    difficulty: "Medium",
    explanation: "In-place algorithms use constant extra space O(1).",
  },
  // DSA - Trees
  {
    id: "dsa-tree-1",
    question: "What is the maximum number of nodes at level L in a binary tree?",
    options: ["L", "2^L", "2L", "L^2"],
    correctAnswer: 1,
    subject: "DSA",
    topic: "Trees",
    difficulty: "Easy",
    explanation: "At level L (starting from 0), maximum nodes = 2^L",
  },
  {
    id: "dsa-tree-2",
    question: "Which traversal gives nodes in sorted order for a BST?",
    options: ["Preorder", "Postorder", "Inorder", "Level Order"],
    correctAnswer: 2,
    subject: "DSA",
    topic: "Trees",
    difficulty: "Easy",
    explanation: "Inorder traversal of BST gives elements in sorted order.",
  },
  {
    id: "dsa-tree-3",
    question: "What is the time complexity of searching in a balanced BST?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    correctAnswer: 2,
    subject: "DSA",
    topic: "Trees",
    difficulty: "Medium",
    explanation: "In a balanced BST, search takes O(log n) time.",
  },
  // DSA - Graphs
  {
    id: "dsa-graph-1",
    question: "Which data structure is used for BFS traversal?",
    options: ["Stack", "Queue", "Heap", "Array"],
    correctAnswer: 1,
    subject: "DSA",
    topic: "Graphs",
    difficulty: "Easy",
    explanation: "BFS uses a queue for level-order traversal.",
  },
  {
    id: "dsa-graph-2",
    question: "What is the time complexity of DFS for adjacency list representation?",
    options: ["O(V)", "O(E)", "O(V+E)", "O(V*E)"],
    correctAnswer: 2,
    subject: "DSA",
    topic: "Graphs",
    difficulty: "Medium",
    explanation: "DFS visits all vertices and edges once, O(V+E).",
  },
  {
    id: "dsa-graph-3",
    question: "Which algorithm finds shortest path in weighted graphs?",
    options: ["BFS", "DFS", "Dijkstra", "Topological Sort"],
    correctAnswer: 2,
    subject: "DSA",
    topic: "Graphs",
    difficulty: "Medium",
    explanation: "Dijkstra's algorithm finds shortest paths in weighted graphs.",
  },
  // DSA - DP
  {
    id: "dsa-dp-1",
    question: "What are the two main properties for DP to be applicable?",
    options: ["Recursion and Iteration", "Optimal Substructure and Overlapping Subproblems", "Divide and Conquer", "Greedy Choice"],
    correctAnswer: 1,
    subject: "DSA",
    topic: "Dynamic Programming",
    difficulty: "Easy",
    explanation: "DP requires optimal substructure and overlapping subproblems.",
  },
  {
    id: "dsa-dp-2",
    question: "What is the time complexity of Fibonacci using memoization?",
    options: ["O(2^n)", "O(n)", "O(n^2)", "O(log n)"],
    correctAnswer: 1,
    subject: "DSA",
    topic: "Dynamic Programming",
    difficulty: "Medium",
    explanation: "Memoization reduces Fibonacci to O(n) by caching results.",
  },
  {
    id: "dsa-dp-3",
    question: "Which approach builds solution from smallest subproblems?",
    options: ["Top-down", "Bottom-up", "Divide and Conquer", "Backtracking"],
    correctAnswer: 1,
    subject: "DSA",
    topic: "Dynamic Programming",
    difficulty: "Easy",
    explanation: "Bottom-up (tabulation) builds from smallest subproblems.",
  },
  // DBMS
  {
    id: "dbms-sql-1",
    question: "Which SQL clause is used to filter grouped results?",
    options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    correctAnswer: 1,
    subject: "DBMS",
    topic: "SQL Queries",
    difficulty: "Easy",
    explanation: "HAVING filters results after GROUP BY aggregation.",
  },
  {
    id: "dbms-sql-2",
    question: "What type of JOIN returns all records from both tables?",
    options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
    correctAnswer: 3,
    subject: "DBMS",
    topic: "SQL Queries",
    difficulty: "Medium",
    explanation: "FULL OUTER JOIN returns all records from both tables.",
  },
  {
    id: "dbms-norm-1",
    question: "Which normal form eliminates transitive dependencies?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    correctAnswer: 2,
    subject: "DBMS",
    topic: "Normalization",
    difficulty: "Medium",
    explanation: "3NF eliminates transitive dependencies on non-key attributes.",
  },
  {
    id: "dbms-trans-1",
    question: "What does ACID stand for in database transactions?",
    options: ["Atomicity, Consistency, Isolation, Durability", "Atomicity, Concurrency, Isolation, Durability", "Atomicity, Consistency, Integration, Durability", "Authentication, Consistency, Isolation, Durability"],
    correctAnswer: 0,
    subject: "DBMS",
    topic: "Transactions",
    difficulty: "Easy",
    explanation: "ACID: Atomicity, Consistency, Isolation, Durability.",
  },
  {
    id: "dbms-trans-2",
    question: "Which isolation level prevents dirty reads but allows phantom reads?",
    options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
    correctAnswer: 1,
    subject: "DBMS",
    topic: "Transactions",
    difficulty: "Hard",
    explanation: "Read Committed prevents dirty reads but allows phantom reads.",
  },
  // OS
  {
    id: "os-proc-1",
    question: "Which scheduling algorithm may cause starvation?",
    options: ["FCFS", "Round Robin", "SJF", "None"],
    correctAnswer: 2,
    subject: "Operating Systems",
    topic: "Process Management",
    difficulty: "Medium",
    explanation: "SJF can cause starvation for longer processes.",
  },
  {
    id: "os-proc-2",
    question: "What is a deadlock?",
    options: ["Process waiting for I/O", "Circular wait among processes", "Process termination", "Memory overflow"],
    correctAnswer: 1,
    subject: "Operating Systems",
    topic: "Process Management",
    difficulty: "Easy",
    explanation: "Deadlock occurs when processes are in circular wait.",
  },
  {
    id: "os-mem-1",
    question: "Which technique divides memory into fixed-size blocks?",
    options: ["Paging", "Segmentation", "Swapping", "Compaction"],
    correctAnswer: 0,
    subject: "Operating Systems",
    topic: "Memory Management",
    difficulty: "Easy",
    explanation: "Paging divides memory into fixed-size pages/frames.",
  },
  // CN
  {
    id: "cn-tcp-1",
    question: "How many handshakes does TCP use to establish a connection?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    subject: "Computer Networks",
    topic: "TCP/IP",
    difficulty: "Easy",
    explanation: "TCP uses a 3-way handshake: SYN, SYN-ACK, ACK.",
  },
  {
    id: "cn-tcp-2",
    question: "Which layer is responsible for end-to-end delivery?",
    options: ["Physical", "Data Link", "Network", "Transport"],
    correctAnswer: 3,
    subject: "Computer Networks",
    topic: "TCP/IP",
    difficulty: "Easy",
    explanation: "Transport layer provides end-to-end data delivery.",
  },
  {
    id: "cn-http-1",
    question: "Which HTTP status code indicates a successful request?",
    options: ["100", "200", "300", "400"],
    correctAnswer: 1,
    subject: "Computer Networks",
    topic: "HTTP/HTTPS",
    difficulty: "Easy",
    explanation: "HTTP 200 OK indicates successful request.",
  },
  // Aptitude
  {
    id: "apt-quant-1",
    question: "If a train travels 300 km in 5 hours, what is its speed?",
    options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
    correctAnswer: 2,
    subject: "Aptitude",
    topic: "Quantitative",
    difficulty: "Easy",
    explanation: "Speed = Distance/Time = 300/5 = 60 km/h",
  },
  {
    id: "apt-quant-2",
    question: "What is 25% of 400?",
    options: ["75", "100", "125", "150"],
    correctAnswer: 1,
    subject: "Aptitude",
    topic: "Quantitative",
    difficulty: "Easy",
    explanation: "25% of 400 = 0.25 × 400 = 100",
  },
  {
    id: "apt-logic-1",
    question: "If all roses are flowers and some flowers are red, which is true?",
    options: ["All roses are red", "Some roses may be red", "No roses are red", "All flowers are roses"],
    correctAnswer: 1,
    subject: "Aptitude",
    topic: "Logical Reasoning",
    difficulty: "Medium",
    explanation: "We can only conclude some roses may be red.",
  },
  {
    id: "apt-logic-2",
    question: "What comes next: 2, 6, 12, 20, ?",
    options: ["28", "30", "32", "36"],
    correctAnswer: 1,
    subject: "Aptitude",
    topic: "Logical Reasoning",
    difficulty: "Medium",
    explanation: "Pattern: n(n+1) where n=1,2,3,4,5 gives 30.",
  },
];
