import type { UserProfile, CompanyProfile } from "./types";

export const userProfile: UserProfile = {
  name: "Alex Chen",
  targetCompany: "Amazon",
  studyStreak: 12,
  totalProblems: 247,
  subjects: [
    {
      name: "DSA",
      icon: "Code2",
      overallProgress: 68,
      overallAccuracy: 72,
      topics: [
        {
          topic: "Arrays",
          subtopics: ["Two Pointers", "Sliding Window", "Prefix Sum"],
          progress: 85,
          accuracy: 88,
          practiceCount: 45,
          lastPracticed: "2024-01-15",
          status: "strong",
        },
        {
          topic: "Trees",
          subtopics: ["Binary Trees", "BST", "Tree Traversal"],
          progress: 70,
          accuracy: 75,
          practiceCount: 32,
          lastPracticed: "2024-01-14",
          status: "moderate",
        },
        {
          topic: "Graphs",
          subtopics: ["BFS", "DFS", "Dijkstra", "Union Find"],
          progress: 45,
          accuracy: 52,
          practiceCount: 18,
          lastPracticed: "2024-01-10",
          status: "weak",
        },
        {
          topic: "Dynamic Programming",
          subtopics: ["1D DP", "2D DP", "Knapsack", "LCS"],
          progress: 38,
          accuracy: 45,
          practiceCount: 22,
          lastPracticed: "2024-01-12",
          status: "weak",
        },
        {
          topic: "Linked Lists",
          subtopics: ["Reversal", "Fast/Slow Pointers", "Merge"],
          progress: 90,
          accuracy: 92,
          practiceCount: 28,
          lastPracticed: "2024-01-13",
          status: "strong",
        },
      ],
    },
    {
      name: "DBMS",
      icon: "Database",
      overallProgress: 55,
      overallAccuracy: 65,
      topics: [
        {
          topic: "SQL Queries",
          subtopics: ["Joins", "Subqueries", "Aggregations"],
          progress: 75,
          accuracy: 80,
          practiceCount: 30,
          lastPracticed: "2024-01-14",
          status: "moderate",
        },
        {
          topic: "Normalization",
          subtopics: ["1NF", "2NF", "3NF", "BCNF"],
          progress: 60,
          accuracy: 70,
          practiceCount: 15,
          lastPracticed: "2024-01-11",
          status: "moderate",
        },
        {
          topic: "Transactions",
          subtopics: ["ACID", "Isolation Levels", "Locking"],
          progress: 40,
          accuracy: 50,
          practiceCount: 10,
          lastPracticed: "2024-01-08",
          status: "weak",
        },
        {
          topic: "Indexing",
          subtopics: ["B+ Trees", "Hashing", "Clustered"],
          progress: 45,
          accuracy: 55,
          practiceCount: 12,
          lastPracticed: "2024-01-09",
          status: "weak",
        },
      ],
    },
    {
      name: "Operating Systems",
      icon: "Cpu",
      overallProgress: 62,
      overallAccuracy: 68,
      topics: [
        {
          topic: "Process Management",
          subtopics: ["Scheduling", "Synchronization", "Deadlocks"],
          progress: 70,
          accuracy: 75,
          practiceCount: 20,
          lastPracticed: "2024-01-13",
          status: "moderate",
        },
        {
          topic: "Memory Management",
          subtopics: ["Paging", "Segmentation", "Virtual Memory"],
          progress: 55,
          accuracy: 60,
          practiceCount: 15,
          lastPracticed: "2024-01-10",
          status: "moderate",
        },
        {
          topic: "File Systems",
          subtopics: ["Allocation", "Directory Structure", "I/O"],
          progress: 65,
          accuracy: 70,
          practiceCount: 12,
          lastPracticed: "2024-01-11",
          status: "moderate",
        },
      ],
    },
    {
      name: "Computer Networks",
      icon: "Network",
      overallProgress: 58,
      overallAccuracy: 62,
      topics: [
        {
          topic: "TCP/IP",
          subtopics: ["Handshake", "Flow Control", "Congestion"],
          progress: 65,
          accuracy: 70,
          practiceCount: 18,
          lastPracticed: "2024-01-12",
          status: "moderate",
        },
        {
          topic: "HTTP/HTTPS",
          subtopics: ["Methods", "Status Codes", "TLS"],
          progress: 80,
          accuracy: 85,
          practiceCount: 22,
          lastPracticed: "2024-01-14",
          status: "strong",
        },
        {
          topic: "DNS",
          subtopics: ["Resolution", "Caching", "Records"],
          progress: 50,
          accuracy: 55,
          practiceCount: 10,
          lastPracticed: "2024-01-08",
          status: "weak",
        },
        {
          topic: "Network Security",
          subtopics: ["Firewalls", "VPN", "Encryption"],
          progress: 40,
          accuracy: 45,
          practiceCount: 8,
          lastPracticed: "2024-01-06",
          status: "weak",
        },
      ],
    },
    {
      name: "Aptitude",
      icon: "Brain",
      overallProgress: 72,
      overallAccuracy: 78,
      topics: [
        {
          topic: "Quantitative",
          subtopics: ["Arithmetic", "Algebra", "Geometry"],
          progress: 80,
          accuracy: 85,
          practiceCount: 40,
          lastPracticed: "2024-01-15",
          status: "strong",
        },
        {
          topic: "Logical Reasoning",
          subtopics: ["Puzzles", "Patterns", "Syllogisms"],
          progress: 75,
          accuracy: 80,
          practiceCount: 35,
          lastPracticed: "2024-01-14",
          status: "moderate",
        },
        {
          topic: "Verbal",
          subtopics: ["Reading Comprehension", "Grammar", "Vocabulary"],
          progress: 60,
          accuracy: 68,
          practiceCount: 20,
          lastPracticed: "2024-01-10",
          status: "moderate",
        },
      ],
    },
  ],
};

export const companies: CompanyProfile[] = [
  {
    name: "Amazon",
    logo: "amazon",
    difficulty: "Hard",
    focusAreas: [
      {
        subject: "DSA",
        weight: 40,
        importantTopics: ["Arrays", "Trees", "Graphs", "Dynamic Programming"],
      },
      {
        subject: "System Design",
        weight: 25,
        importantTopics: ["Scalability", "Distributed Systems"],
      },
      {
        subject: "Leadership Principles",
        weight: 20,
        importantTopics: ["Behavioral Questions", "STAR Method"],
      },
      {
        subject: "DBMS",
        weight: 15,
        importantTopics: ["SQL Queries", "Indexing"],
      },
    ],
    interviewRounds: [
      "Online Assessment",
      "Phone Screen",
      "On-site (4-5 rounds)",
    ],
  },
  {
    name: "TCS",
    logo: "tcs",
    difficulty: "Medium",
    focusAreas: [
      {
        subject: "Aptitude",
        weight: 35,
        importantTopics: ["Quantitative", "Logical Reasoning", "Verbal"],
      },
      { subject: "DSA", weight: 25, importantTopics: ["Arrays", "Strings"] },
      {
        subject: "DBMS",
        weight: 20,
        importantTopics: ["SQL Queries", "Normalization"],
      },
      {
        subject: "OS & CN",
        weight: 20,
        importantTopics: ["Process Management", "TCP/IP"],
      },
    ],
    interviewRounds: ["NQT Test", "Technical Interview", "HR Interview"],
  },
  {
    name: "Infosys",
    logo: "infosys",
    difficulty: "Medium",
    focusAreas: [
      {
        subject: "Aptitude",
        weight: 30,
        importantTopics: ["Quantitative", "Logical Reasoning"],
      },
      {
        subject: "DSA",
        weight: 30,
        importantTopics: ["Arrays", "Linked Lists", "Trees"],
      },
      {
        subject: "DBMS",
        weight: 20,
        importantTopics: ["SQL Queries", "Transactions"],
      },
      { subject: "OS", weight: 20, importantTopics: ["Process Management"] },
    ],
    interviewRounds: ["InfyTQ", "Technical Interview", "HR Interview"],
  },
  {
    name: "Google",
    logo: "google",
    difficulty: "Hard",
    focusAreas: [
      {
        subject: "DSA",
        weight: 50,
        importantTopics: ["Graphs", "Dynamic Programming", "Trees", "Arrays"],
      },
      {
        subject: "System Design",
        weight: 30,
        importantTopics: ["Distributed Systems", "API Design"],
      },
      {
        subject: "Behavioral",
        weight: 20,
        importantTopics: ["Googleyness", "Leadership"],
      },
    ],
    interviewRounds: [
      "Phone Screen (2)",
      "On-site (4-5 rounds)",
      "Team Matching",
    ],
  },
];
